# Generated by Django 4.2.7 on 2023-11-27 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "category_name",
                    models.CharField(max_length=100, verbose_name="Category Name"),
                ),
                (
                    "font_awesome",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Font Awesome",
                    ),
                ),
                (
                    "logo_url",
                    models.ImageField(
                        blank=True,
                        help_text="Allowed size is 5MB",
                        null=True,
                        upload_to="categories/",
                        verbose_name="Icon",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "shop_name",
                    models.CharField(max_length=100, verbose_name="Shop Name"),
                ),
                ("tel", models.CharField(max_length=20, verbose_name="Tel")),
                ("fax", models.CharField(max_length=20, verbose_name="Fax")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                (
                    "website",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Website"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Twitter"
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Facebook"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="LinkedIn"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Instagram"
                    ),
                ),
                ("address", models.CharField(max_length=250, verbose_name="Address")),
                ("latitude", models.FloatField(default=0, verbose_name="Latitude")),
                ("longitude", models.FloatField(default=0, verbose_name="Longitude")),
                (
                    "banner_url",
                    models.ImageField(
                        blank=True,
                        help_text="Allow size is 10MB",
                        null=True,
                        upload_to="shops/banners/%Y-%m-%d/",
                        verbose_name="Banner URL",
                    ),
                ),
                (
                    "logo_url",
                    models.ImageField(
                        blank=True,
                        help_text="Allow size is 5MB",
                        null=True,
                        upload_to="shops/logos/%Y-%m-%d/",
                        verbose_name="Logo URL",
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="About"),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Shops",},
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "first_name",
                    models.CharField(max_length=25, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=25, verbose_name="Last Name"),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Tel"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "ssn",
                    models.CharField(
                        max_length=15, verbose_name="Social Security Number"
                    ),
                ),
                (
                    "photo_url",
                    models.ImageField(
                        blank=True,
                        help_text="Allow size is 10MB",
                        null=True,
                        upload_to="avatars/staffs/%Y-%m-%d/",
                        verbose_name="Photo URL",
                    ),
                ),
                (
                    "shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.shop",
                        verbose_name="Shop",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Staffs",},
        ),
        migrations.CreateModel(
            name="ShopService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "service_id",
                    models.ManyToManyField(
                        related_name="service",
                        to="service.service",
                        verbose_name="Service",
                    ),
                ),
                (
                    "shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop",
                        to="shop.shop",
                        verbose_name="Shop",
                    ),
                ),
            ],
            options={"verbose_name_plural": "ShopServices",},
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "photo_url",
                    models.ImageField(
                        blank=True,
                        help_text="Allow size is 20MB",
                        null=True,
                        upload_to="services/galleries/%Y-%m-%d/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.shop",
                        verbose_name="Shop",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Galleries",},
        ),
        migrations.CreateModel(
            name="BusinessHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("day", models.CharField(max_length=15, verbose_name="Day")),
                ("hour", models.CharField(max_length=15, verbose_name="Hour")),
                (
                    "shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.shop",
                        verbose_name="Shop",
                    ),
                ),
            ],
            options={"verbose_name_plural": "BusinessHours",},
        ),
    ]
