# Generated by Django 4.2.7 on 2023-11-27 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("service", "0001_initial"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "platform_name",
                    models.CharField(
                        choices=[
                            ("All", "All"),
                            ("Web", "Web"),
                            ("iOS", "iOS"),
                            ("Android", "Android"),
                        ],
                        default="All",
                        max_length=15,
                        verbose_name="Platform Name",
                    ),
                ),
                ("ip", models.CharField(max_length=20, verbose_name="IP Address")),
                ("device", models.CharField(max_length=20, verbose_name="Device")),
                ("uuid", models.CharField(max_length=250, verbose_name="UUID")),
            ],
            options={"verbose_name_plural": "Platforms",},
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("subtitle", models.CharField(max_length=250, verbose_name="SubTitle")),
                (
                    "color",
                    models.CharField(
                        default="#",
                        help_text="Hex Color [Ex: #C3C3C3]",
                        max_length=10,
                        verbose_name="Color",
                    ),
                ),
                (
                    "photo_url",
                    models.ImageField(
                        help_text="Allow size is 10MB",
                        upload_to="settings/promotions/%Y-%m-%d/",
                        verbose_name="Photo URL",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "service_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.service",
                        verbose_name="Service",
                    ),
                ),
                (
                    "shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.shop",
                        verbose_name="Shop",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Promotions",},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "subtitle",
                    models.CharField(max_length=250, verbose_name="Sub Title"),
                ),
                (
                    "photo_url",
                    models.ImageField(
                        help_text="Allowed size is 20MB",
                        upload_to="notifications/%Y-%m-%d/",
                        verbose_name="Photo URL",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                (
                    "platform_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting.platform",
                        verbose_name="Platform",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Notifications",},
        ),
    ]
